### PR TITLE
synchronize useragent parser for thread safety

### LINKED ISSUE #25: random failures
useragent parsing randomly produces the following style of errors:

```
Uknown error while parsing user agent data {:exception=>java.lang.ArrayIndexOutOfBoundsException
```

By adding tracing, I can see that these failures happen within the JRuby regex matching code, in the parser call at https://github.com/logstash-plugins/logstash-filter-useragent/blob/e0527955facec973ac97981cb17f84df242fac1b/lib/logstash/filters/useragent.rb#L123 - see stacktrace below.

The problem is that these occur randomly, and not systematically reproductible. As this feel like a concurrency problem, I tried forcing a single worker `- w 1` and in fact I cannot trigger the problem with a single worker. So it seems the problem is related to parser thread safety.

Stacktrace (not that line numbers are a bit off because of locally added tracing):
```
org.jcodings.specific.BaseUTF8Encoding.mbcCaseFold(BaseUTF8Encoding.java:167)
org.jcodings.specific.UTF8Encoding.mbcCaseFold(UTF8Encoding.java:24)
org.joni.SearchAlgorithm$SLOW_IC.lowerCaseMatch(SearchAlgorithm.java:238)
org.joni.SearchAlgorithm$SLOW_IC.search(SearchAlgorithm.java:206)
org.joni.Matcher.forwardSearchRange(Matcher.java:140)
org.joni.Matcher.searchInterruptible(Matcher.java:451)
org.jruby.RubyRegexp$SearchMatchTask.run(RubyRegexp.java:273)
org.jruby.RubyThread.executeBlockingTask(RubyThread.java:1066)
org.jruby.RubyRegexp.matcherSearch(RubyRegexp.java:235)
org.jruby.RubyRegexp.search19(RubyRegexp.java:1780)
org.jruby.RubyRegexp.matchPos(RubyRegexp.java:1720)
org.jruby.RubyRegexp.match19Common(RubyRegexp.java:1701)
org.jruby.RubyRegexp.match_m19(RubyRegexp.java:1680)
org.jruby.RubyRegexp$INVOKER$i$match_m19.call(RubyRegexp$INVOKER$i$match_m19.gen)
org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:350)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
rubyjit.UserAgentParser::Parser$$first_pattern_match_8f4efbc71f9ee811dc0b66b55c435a7b33342f701163157884.block_0$RUBY$__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb:66)
rubyjit$UserAgentParser::Parser$$first_pattern_match_8f4efbc71f9ee811dc0b66b55c435a7b33342f701163157884$block_0$RUBY$__file__.call(rubyjit$UserAgentParser::Parser$$first_pattern_match_8f4efbc71f9ee811dc0b66b55c435a7b33342f701163157884$block_0$RUBY$__file__)
org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
org.jruby.runtime.Block.yield(Block.java:142)
org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
org.jruby.RubyArray.each(RubyArray.java:1613)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
rubyjit.UserAgentParser::Parser$$first_pattern_match_8f4efbc71f9ee811dc0b66b55c435a7b33342f701163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb:65)
rubyjit.UserAgentParser::Parser$$first_pattern_match_8f4efbc71f9ee811dc0b66b55c435a7b33342f701163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:221)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
rubyjit.UserAgentParser::Parser$$parse_device_d0c1065ac69f949442017c87599f1e7aace77f7e1163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb:55)
rubyjit.UserAgentParser::Parser$$parse_device_d0c1065ac69f949442017c87599f1e7aace77f7e1163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
rubyjit.UserAgentParser::Parser$$parse_51ebdc04849f3aa7235fcc4fcda263f2adf486291163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb:15)
rubyjit.UserAgentParser::Parser$$parse_51ebdc04849f3aa7235fcc4fcda263f2adf486291163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/user_agent_parser-2.3.0/lib/user_agent_parser/parser.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
rubyjit.LogStash::Filters::UserAgent$$lookup_useragent_4606667f95ea0ad9d6e00f1c2963674d1c5b3b0f1163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-filter-useragent/lib/logstash/filters/useragent.rb:124)
rubyjit.LogStash::Filters::UserAgent$$lookup_useragent_4606667f95ea0ad9d6e00f1c2963674d1c5b3b0f1163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-filter-useragent/lib/logstash/filters/useragent.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
rubyjit.LogStash::Filters::UserAgent$$filter_54b6215f281b867e88fb4a4898694e2b351a1b891163157884.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-filter-useragent/lib/logstash/filters/useragent.rb:101)
rubyjit.LogStash::Filters::UserAgent$$filter_54b6215f281b867e88fb4a4898694e2b351a1b891163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-filter-useragent/lib/logstash/filters/useragent.rb:100)
rubyjit.LogStash::Filters::UserAgent$$filter_54b6215f281b867e88fb4a4898694e2b351a1b891163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash-plugins/logstash-filter-useragent/lib/logstash/filters/useragent.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)
rubyjit.LogStash::Filters::Base$$multi_filter_01135e7048cf29d1ffa54e153def77da0a7b31831163157884.block_0$RUBY$__file__(/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/filters/base.rb:151)
rubyjit$LogStash::Filters::Base$$multi_filter_01135e7048cf29d1ffa54e153def77da0a7b31831163157884$block_0$RUBY$__file__.call(rubyjit$LogStash::Filters::Base$$multi_filter_01135e7048cf29d1ffa54e153def77da0a7b31831163157884$block_0$RUBY$__file__)
org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
org.jruby.runtime.Block.yield(Block.java:142)
org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
org.jruby.RubyArray.each(RubyArray.java:1613)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
rubyjit.LogStash::Filters::Base$$multi_filter_01135e7048cf29d1ffa54e153def77da0a7b31831163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/filters/base.rb:148)
rubyjit.LogStash::Filters::Base$$multi_filter_01135e7048cf29d1ffa54e153def77da0a7b31831163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/filters/base.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
rubyjit.LogStash::FilterDelegator$$multi_filter_d98741d7b174f7016a83a8b3eede266464b685891163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/filter_delegator.rb:40)
rubyjit.LogStash::FilterDelegator$$multi_filter_d98741d7b174f7016a83a8b3eede266464b685891163157884.__file__(/Users/colin/dev/src/elasticsearch/logstash/logstash-core/lib/logstash/filter_delegator.rb)
org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
org.jruby.runtime.Block.call(Block.java:101)
org.jruby.RubyProc.call(RubyProc.java:300)
org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
org.jruby.ast.DAsgnNode.interpret(DAsgnNode.java:110)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.ast.IfNode.interpret(IfNode.java:116)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:177)
org.jruby.runtime.Block.yieldArray(Block.java:158)
org.jruby.RubyEnumerable$25.call(RubyEnumerable.java:835)
org.jruby.runtime.CallBlock.yield(CallBlock.java:90)
org.jruby.runtime.Block.yield(Block.java:142)
org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
org.jruby.RubyArray.each(RubyArray.java:1613)
org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
org.jruby.RubyClass.finvoke(RubyClass.java:528)
org.jruby.runtime.Helpers.invoke(Helpers.java:486)
org.jruby.RubyEnumerable.callEach(RubyEnumerable.java:98)
org.jruby.RubyEnumerable.injectCommon(RubyEnumerable.java:831)
org.jruby.RubyEnumerable.inject(RubyEnumerable.java:852)
org.jruby.RubyEnumerable$INVOKER$s$inject.call(RubyEnumerable$INVOKER$s$inject.gen)
org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)
org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)
org.jruby.ast.CallOneArgBlockNode.interpret(CallOneArgBlockNode.java:60)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
org.jruby.runtime.Block.call(Block.java:101)
org.jruby.RubyProc.call(RubyProc.java:300)
org.jruby.RubyProc.call(RubyProc.java:230)
org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by colinsurprenant**
fixes #25 

wrap `UserAgentParser::Parser#parser` in a mutex to avoid thread safety issues. The real cause seems to be related to the underlying JRuby regex code that is not thread safe but in any case, this is pretty much this only fix possible at this point.

I have manually confirmed that this solves the problem. using a big enough dataset (>= 5000 lines) and using multiple workers, a few random errors are usually triggered. Using this fix (or setting the number of workers to 1) the error in never triggered.

### CODE REVIEW

File: lib/logstash/filters/useragent.rb [hunk 1]
```diff
@@ -120,7 +122,10 @@ def lookup_useragent(useragent)
     cached = LOOKUP_CACHE[useragent]
     return cached if cached
 
-    ua_data = @parser.parse(useragent)
+    # the UserAgentParser::Parser class is not thread safe, indications are that it is probalby
```
Comment (ph) [inline lib/logstash/filters/useragent.rb]: probalby=> probably

**Comment by ph** [comment]
LGTM, I am OK with that change + explanation.

**Comment by ph** [comment]
In you traces, you have isolated it the jruby / regexp handling. I am wondering how we should consider this problem, it is a problem in jruby itself and we need to create an issue on their repository OR its is an implementation problem and we should take extra care for thread satefy when working with regex? WDYT?

**Comment by colinsurprenant** [comment]
@ph agree, https://github.com/elastic/logstash/issues/4977

**Comment by colinsurprenant** [comment]
bumped + published version 2.0.7

**Comment by outcoldman** [comment]
Which version has this fix?
I see this issue in logstash 5.4.2
